[package]
name          = "ecdsa"
version       = "0.3.0" # Also update html_root_url in lib.rs when bumping this
description   = """
Signature and elliptic curve types providing interoperable support for the
Elliptic Curve Digital Signature Algorithm (ECDSA)
"""
authors       = ["RustCrypto Developers"]
license       = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/ecdsa"
repository    = "https://github.com/RustCrypto/signatures"
edition       = "2018"
readme        = "README.md"
categories    = ["cryptography", "no-std"]
keywords      = ["crypto", "ecc", "nist", "secp256k1", "signature"]

[dependencies.elliptic-curve]
version = "0.2.0"
path = "../elliptic-curve-crate"
default-features = false
features = ["weierstrass"]

[dependencies.generic-array]
version = "0.12"
default-features = false

[dependencies.sha2]
version = "0.8"
optional = true
default-features = false

[dependencies.signature]
version = "1.0.0-pre.1"
path = "../signature-crate"
default-features = false

[features]
default = ["digest", "std", "zeroize"]
digest = ["signature/digest-preview", "sha2"]
std = ["elliptic-curve/getrandom", "elliptic-curve/std", "signature/std"]
zeroize = ["elliptic-curve/zeroize"]
test-vectors = []

[package.metadata.docs.rs]
all-features = true
