[package]
name          = "ecdsa"
version       = "0.0.0"
authors       = ["RustCrypto Developers"]
license       = "Apache-2.0 OR MIT"
description   = "Elliptic Curve Digital Signature Algorithm"
documentation = "https://docs.rs/ecdsa"
repository    = "https://github.com/RustCrypto/signatures"
edition       = "2018"
categories    = ["cryptography", "no-std"]
keywords      = ["crypto", "ecc", "ecdsa", "signature", "signing"]

[dependencies.generic-array]
version = "0.12"
default-features = false

[dependencies.sha2]
version = "0.8"
optional = true
default-features = false

[dependencies.signature]
version = "1.0.0-pre.1"
path = "../signature-crate"
default-features = false

[features]
default = ["digest", "std"]
digest = ["signature/digest-preview", "sha2"]
std = ["signature/std"]
test-vectors = []

[package.metadata.docs.rs]
all-features = true
