[package]
name = "ecdsa"
version = "0.0.0"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
description = "Elliptic Curve Digital Signature Algorithm"
documentation = "https://docs.rs/ecdsa"
repository = "https://github.com/RustCrypto/signatures"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "ecc", "ecdsa", "signature", "signing"]

[dependencies]
signature = { version = "1.0.0-pre", path = "../signature-crate" }
